//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsWork.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsStatusDetailsSet
    {
        public int Id { get; set; }
        public int AccountMainId { get; set; }
        public string AccountStatus { get; set; }
        public System.DateTime AccountStatusDate { get; set; }
        public string Commentary { get; set; }
        public Nullable<int> AccountPayNumber { get; set; }
    
        public virtual AccountsMainSet AccountsMainSet { get; set; }
    }
}
