//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsWork.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsStoreDetailsSet
    {
        public int Id { get; set; }
        public int AccountsMainId { get; set; }
        public int AccountStore { get; set; }
    
        public virtual AccountsMainSet AccountsMainSet { get; set; }
        public virtual StoresSet StoresSet { get; set; }
    }
}
