//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsWork.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsMainSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountsMainSet()
        {
            this.AccountsBudgetDetailsSets = new HashSet<AccountsBudgetDetailsSet>();
            this.AccountsCapexInfoSets = new HashSet<AccountsCapexInfoSet>();
            this.AccountsStatusDetailsSets = new HashSet<AccountsStatusDetailsSet>();
            this.AccountsStoreDetailsSets = new HashSet<AccountsStoreDetailsSet>();
            this.StoreProvenWorkSets = new HashSet<StoreProvenWorkSet>();
        }
    
        public int Id { get; set; }
        public string AccountNumber { get; set; }
        public string AccountCompany { get; set; }
        public System.DateTime AccountDate { get; set; }
        public decimal AccountAmount { get; set; }
        public string AccountDescription { get; set; }
        public string AccountMcdType { get; set; }
        public Nullable<int> AccountYear { get; set; }
        public string AccountType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountsBudgetDetailsSet> AccountsBudgetDetailsSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountsCapexInfoSet> AccountsCapexInfoSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountsStatusDetailsSet> AccountsStatusDetailsSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountsStoreDetailsSet> AccountsStoreDetailsSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreProvenWorkSet> StoreProvenWorkSets { get; set; }
    }
}
