//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsWork.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsCapexInfoSet
    {
        public int Id { get; set; }
        public int AccountsMainId { get; set; }
        public string AccountCapexName { get; set; }
        public decimal AccountCapexAmount { get; set; }
        public string AccountExpense { get; set; }
        public int CapexId { get; set; }
    
        public virtual AccountsMainSet AccountsMainSet { get; set; }
        public virtual CapexSet CapexSet { get; set; }
    }
}
