//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsWork.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsCapexInfoSet
    {
        public int Id { get; set; }
        public int AccountsMainId { get; set; }
        public string AccountCapexName { get; set; }
        public decimal AccountCapexAmount { get; set; }
        public string AccountExpense { get; set; }
        public int CapexId { get; set; }
    
        public virtual AccountsMainSet AccountsMainSet { get; set; }
        public virtual CapexSet CapexSet { get; set; }
    }
}
