//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsWork.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsBudgetDetailsSet
    {
        public int Id { get; set; }
        public int AccountsMainId { get; set; }
        public string AccountEquipmentName { get; set; }
        public int AccountEquipmentQuantity { get; set; }
        public decimal AccountEquipmentPrice { get; set; }
        public int AccountStoreNumber { get; set; }
        public int EquipmentCapexId { get; set; }
        public string EquipmentCapexName { get; set; }
    
        public virtual AccountsMainSet AccountsMainSet { get; set; }
        public virtual CapexSet CapexSet { get; set; }
    }
}
