//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsWork.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsBudgetDetailsSet
    {
        public int Id { get; set; }
        public int AccountsMainId { get; set; }
        public string AccountEquipmentName { get; set; }
        public int AccountEquipmentQuantity { get; set; }
        public decimal AccountEquipmentPrice { get; set; }
        public int BudgetId { get; set; }
        public int AccountStoreNumber { get; set; }
    
        public virtual StoresSet StoresSet { get; set; }
        public virtual AccountsMainSet AccountsMainSet { get; set; }
        public virtual BudgetSet BudgetSet { get; set; }
    }
}
