//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsWork.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetSet
    {
        public int Id { get; set; }
        public string BudgetEquipmentName { get; set; }
        public int BudgetQuantity { get; set; }
        public decimal BudgetPrice { get; set; }
        public int BudgetYear { get; set; }
    }
}
