//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsWork.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceZipDetailsSet
    {
        public int Id { get; set; }
        public string ZipName { get; set; }
        public string ServiceMonth { get; set; }
        public System.DateTime WorkDate { get; set; }
        public string BlankNumber { get; set; }
        public Nullable<int> ZipQuantity { get; set; }
        public int StoreNumber { get; set; }
        public decimal ZipPrice { get; set; }
        public string Company { get; set; }
    
        public virtual StoresSet StoresSet { get; set; }
        public virtual ZipSet ZipSet { get; set; }
    }
}
