//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsWork.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoresSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StoresSet()
        {
            this.AccountsBudgetDetailsSets = new HashSet<AccountsBudgetDetailsSet>();
            this.AccountsStoreDetailsSets = new HashSet<AccountsStoreDetailsSet>();
            this.ServiceZipDetailsSets = new HashSet<ServiceZipDetailsSet>();
            this.StoreProvenWorkSets = new HashSet<StoreProvenWorkSet>();
        }
    
        public int StoreNumber { get; set; }
        public string StoreName { get; set; }
        public string StoreType { get; set; }
        public string StoreRegion { get; set; }
        public string StoreCompany { get; set; }
        public Nullable<System.DateTime> StoreOpenDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountsBudgetDetailsSet> AccountsBudgetDetailsSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountsStoreDetailsSet> AccountsStoreDetailsSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceZipDetailsSet> ServiceZipDetailsSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreProvenWorkSet> StoreProvenWorkSets { get; set; }
    }
}
