//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsWork.DomainModel
{
    using Infrastructure;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class StoresSet : ValidatableBindableBase
    {
        private int _id;
        private string _storeName;
        private string _storeType;
        private string _storeRegion;
        private string _storeCompany;
        private DateTime? _storeOpenDate;
        private DateTime? _storeCloseDate;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StoresSet()
        {
            this.AccountsBudgetDetailsSets = new HashSet<AccountsBudgetDetailsSet>();
            this.AccountsStoreDetailsSets = new HashSet<AccountsStoreDetailsSet>();
            this.ServiceZipDetailsSets = new HashSet<ServiceZipDetailsSet>();
            this.StoreProvenWorkSets = new HashSet<StoreProvenWorkSet>();
        }
        [Required]
        public int StoreNumber
        {
            get { return _id; }
            set { SetProperty(ref _id, value); }
        }
        [Required]
        public string StoreName
        {
            get { return _storeName; }
            set { SetProperty(ref _storeName, value); }
        }
        [Required]
        public string StoreType
        {
            get { return _storeType; }
            set { SetProperty(ref _storeType, value); }
        }
        [Required]
        public string StoreRegion
        {
            get { return _storeRegion; }
            set { SetProperty(ref _storeRegion, value); }
        }
        [Required]
        public string StoreCompany
        {
            get { return _storeCompany; }
            set { SetProperty(ref _storeCompany, value); }
        }

        public Nullable<System.DateTime> StoreOpenDate
        {
            get { return _storeOpenDate; }
            set { SetProperty(ref _storeOpenDate, value); }
        }
        public Nullable<System.DateTime> StoreCloseDate
        {
            get { return _storeCloseDate; }
            set { SetProperty(ref _storeCloseDate, value); }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountsBudgetDetailsSet> AccountsBudgetDetailsSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountsStoreDetailsSet> AccountsStoreDetailsSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceZipDetailsSet> ServiceZipDetailsSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreProvenWorkSet> StoreProvenWorkSets { get; set; }
    }
}
