//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsWork.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreProvenWorkSet
    {
        public int Id { get; set; }
        public int StoreNumber { get; set; }
        public System.DateTime StoreDateOfConfirm { get; set; }
        public string StoreWork { get; set; }
        public Nullable<int> MainAccountId { get; set; }
        public bool IsDone { get; set; }
    
        public virtual AccountsMainSet AccountsMainSet { get; set; }
        public virtual StoresSet StoresSet { get; set; }
    }
}
