//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsWork.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreProvenWorkSet
    {
        public int Id { get; set; }
        public int StoreNumber { get; set; }
        public System.DateTime StoreDateOfConfirm { get; set; }
        public string StoreWork { get; set; }
        public Nullable<int> MainAccountId { get; set; }
        public bool IsDone { get; set; }
    
        public virtual AccountsMainSet AccountsMainSet { get; set; }
        public virtual StoresSet StoresSet { get; set; }
    }
}
