//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsWork.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using AccountsWork.DomainModel;
    
    public partial class AccountsEntities : DbContext
    {
        public AccountsEntities()
            : base("name=AccountsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountsBudgetDetailsSet> AccountsBudgetDetailsSets { get; set; }
        public virtual DbSet<AccountsCapexInfoSet> AccountsCapexInfoSets { get; set; }
        public virtual DbSet<AccountsCompaniesSet> AccountsCompaniesSets { get; set; }
        public virtual DbSet<AccountsExpenseSet> AccountsExpenseSets { get; set; }
        public virtual DbSet<AccountsMainSet> AccountsMainSets { get; set; }
        public virtual DbSet<AccountsStatusDetailsSet> AccountsStatusDetailsSets { get; set; }
        public virtual DbSet<AccountsStoreDetailsSet> AccountsStoreDetailsSets { get; set; }
        public virtual DbSet<BudgetSet> BudgetSets { get; set; }
        public virtual DbSet<CapexSet> CapexSets { get; set; }
        public virtual DbSet<ServiceZipDetailsSet> ServiceZipDetailsSets { get; set; }
        public virtual DbSet<StoreProvenWorkSet> StoreProvenWorkSets { get; set; }
        public virtual DbSet<StoresSet> StoresSets { get; set; }
        public virtual DbSet<TypeSet> TypeSets { get; set; }
        public virtual DbSet<ZipSet> ZipSets { get; set; }
    }
}
