//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountsWork.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using AccountsWork.DomainModel;
    
    public partial class AccountsEntities : DbContext
    {
        public AccountsEntities()
            : base("name=AccountsEntities")
        {
            Configuration.LazyLoadingEnabled = false;
            Configuration.ProxyCreationEnabled = false;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccountsBudgetDetailsSet> AccountsBudgetDetailsSets { get; set; }
        public DbSet<AccountsCapexInfoSet> AccountsCapexInfoSets { get; set; }
        public DbSet<AccountsCompaniesSet> AccountsCompaniesSets { get; set; }
        public DbSet<AccountsExpenseSet> AccountsExpenseSets { get; set; }
        public DbSet<AccountsMainSet> AccountsMainSets { get; set; }
        public DbSet<AccountsStatusDetailsSet> AccountsStatusDetailsSets { get; set; }
        public DbSet<AccountsStoreDetailsSet> AccountsStoreDetailsSets { get; set; }
        public DbSet<BudgetSet> BudgetSets { get; set; }
        public DbSet<CapexSet> CapexSets { get; set; }
        public DbSet<ServiceZipDetailsSet> ServiceZipDetailsSets { get; set; }
        public DbSet<StoreProvenWorkSet> StoreProvenWorkSets { get; set; }
        public DbSet<StoresSet> StoresSets { get; set; }
        public DbSet<TypeSet> TypeSets { get; set; }
        public DbSet<ZipSet> ZipSets { get; set; }
    }
}
